spring:
  application:
    name: eureka-server
server:
  port: 8763
eureka:
  client:
    register-with-eureka: false #禁止自已做为服务注册到服务上
    fetch-registry: false #禁止拿注册列表
    service-url:
       defaultZone: http://locahost:8762/eureka/ #注册中心地址
logging:
  config:
  level: debug
